"""add timestamp and soft delete mixins to posts and comments.

Revision ID: 5712b1d697b5
Revises: 4a7de83049db
Create Date: 2025-10-31 18:02:48.834999

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5712b1d697b5"
down_revision = "4a7de83049db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("comments", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column(
        "posts",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("posts", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "is_deleted")
    op.drop_column("posts", "updated_at")
    op.drop_column("comments", "is_deleted")
    op.drop_column("comments", "updated_at")
    # ### end Alembic commands ###
